### ISSUE TITLE
Unclear Licensing

### ISSUE THREAD

**Issue by sdfgeoff** [SPOCKnots/pyknotid#2]
No licensing information for this library can be found in the git repository or on the documentation website.

If no license has been decided on, I would suggest the GPL or MIT license.

**Comment by inclement** [comment]
Thanks for raising the issue, and sorry for the delay replying (I actually missed this, but I've fixed my notification settings now).

pyknotid is now available under the MIT license. The delay in making this clear was due to waiting for an official okay about it, which took longer than expected. I've now added the license and will update the documentation appropriately.

**Comment by sdfgeoff** [comment]
Thanks
